### ISSUE TITLE
Located multiple bootstrappers problem

### ISSUE THREAD

**Issue by petterl** [thesheps/nancy.openapi#5]
When adding the Nuget I get a problem that my bootstraper and the one in OpenApi interfere.

    Located multiple bootstrappers:
    - Web.Api.Core.ApiBootstrapper
    - Nancy.OpenApi.Infrastructure.Bootstrapper

    Either remove unused bootstrapper types or specify which type to use.

Where the first one is my bootstraper and the second comes from the nuget package.

Whats the correct procedure to fix this?

**Comment by wickstargazer** [comment]
How was this fixed?

**Comment by petterl** [comment]
I have no solution, and stared looking at other openapi libraries instead.
But if you know any solution I'm happy to move back.

**Comment by thesheps** [comment]
Hey Petter so sorry!!! I've been absolutely snowed in so not had a chance
to take a look. I'll review at lunch but I think from memory if you
subclass the OpenApiBootstrapper with your production one you should be safe

**Comment by petterl** [comment]
Unfortunately we already subclass  StructureMapNancyBootstrapper since we use structuremap

**Comment by wickstargazer** [comment]
is there a way then to ignore the bootstraper and then copy the code. its
only a few lines of code. although subclass did work

**Comment by thesheps** [comment]
Yeah of course. Apologies once again for being a shitty, uncommunicative
dev! I should be able to find some time today to work on this. The cruft of
the openapi bootstrapper is probably an ideal candidate to move into an
extension method somewhere, just need to figure it out :)

**Comment by petterl** [comment]
Any progress @thesheps?

**Comment by mferry4act** [comment]
@thesheps, any progress or update on this issue?

**Comment by thesheps** [comment]
So I've finally found some time to actually look at this and I'm preparing to submit a fix right now, apologies everyone for having been so tardy on this!

Unfortunately this is going to be a breaking change.  I wanted as much as possible to go down the super-duper-happy path with this but as you guys have rightfully pointed out you can't have multiple bootstrappers live adjacent to each other and I know this is causing a lot of conflict.  What I'm proposing is a re-write of the implementation such that you keep your OWN bootstrapper as-is, and simply override the NancyConfiguration thus:

`protected override NancyInternalConfiguration InternalConfiguration => this.WithOpenApi(Conventions, ApplicationContainer)`

This is achieved through adding a few different extension methods, but crucially also by killing the OpenApi Bootstrapper I'd previously written.  It all looks fine from my perspective and is still serving up the delicious Swagger docs out to ~/api-docs, and all my tests are passing.

**Comment by wickstargazer** [comment]
Hi what i did was simply to inherit from the bootstrapper and override the
function

 protected override void ConfigureApplicationContainer(TinyIoCContainer
container)
        {
            base.ConfigureApplicationContainer(container);

            var assembly = typeof(OpenApiModule).Assembly;

            if
(!ResourceViewLocationProvider.RootNamespaces.ContainsKey(assembly))
                ResourceViewLocationProvider.RootNamespaces.Add(assembly,
"Nancy.OpenApi.SwaggerUi");


            container.Register<JsonSerializer,
JsonNetSerializer>().AsSingleton();

        }

i think that solved the issue

**Comment by thesheps** [comment]
Thanks for the heads up on that - still doesn't fix the issue whereby
people are already using a third party bootstrapper such as the
AutofacBootstrapper etc.  Great shout though :)

**Comment by wickstargazer** [comment]
Hey guys, Sorry i was off with the fix, what i did was forked the project and added this

` type = AppDomain.CurrentDomain.GetAssemblies().Where(a => !Bootstrapper.DefaultAutoRegisterIgnoredAssemblies.Any(ia => ia(a)))`

to this function ` public RouteMetadataProvider(TinyIoCContainer container)`

Committed the fork and its working fine ... https://github.com/wickstargazer/nancy.openapi

Does the fix work as well? haven't tried but will do soon :D

Regards,
Wick

**Comment by webartoli** [comment]
if you are including `Nancy.Hosting.Aspnet` package, you can specify it on a `web.config` file adding the `nancyFx` section as described below:



``` xml
<configuration>
  <configSections>
    <section name="nancyFx" type="Nancy.Hosting.Aspnet.NancyFxSection" />
  </configSections>
  <nancyFx>
    <bootstrapper assembly="Web.Api.Core" type="Web.Api.Core.ApiBootstrapper" />
  </nancyFx>
</configuration>
```

Additional informations can be found on Hosting section in NancyFx github wiki: 
https://github.com/NancyFx/Nancy/wiki/Hosting-Nancy-with-asp.net#bootstrapping
